(require 'ert)

(defconst repo-root
  (file-name-directory
   (directory-file-name
    (file-name-directory (or load-file-name buffer-file-name)))))

(defun repo-file (name)
  (expand-file-name name repo-root))

(defun file-content (name)
  (with-temp-buffer
    (insert-file-contents (repo-file name))
    (buffer-string)))

(ert-deftest config-org-should-exist ()
  (should (file-exists-p (repo-file "config.org"))))

(ert-deftest init-should-load-config-org ()
  (let ((content (file-content "init.el")))
    (should (string-match-p "local\\.el" content))
    (should (string-match-p "org-babel-load-file" content))
    (should (string-match-p "config\\.org" content))))

(ert-deftest config-should-use-emacs-native-keybindings ()
  (let ((content (file-content "config.org")))
    (should-not (string-match-p "\\bevil\\b" content))
    (should-not (string-match-p "\\bkey-chord\\b" content))
    (should-not (string-match-p "\\bgeneral\\b" content))
    (should (string-match-p "(kbd \"C-c a\") #'org-agenda" content))
    (should (string-match-p "(kbd \"C-c c\") #'my/orgfiles-capture-dispatch" content))
    (should (string-match-p "(kbd \"C-c T\") #'org-todo-list" content))
    (should (string-match-p "(kbd \"C-c q\") #'quit-window" content))
    (should (string-match-p "org-agenda-mode-map" content))
    (should (string-match-p "(kbd \"C-c q\") #'org-agenda-quit" content))))

(ert-deftest config-should-have-project-and-statusline ()
  (let ((content (file-content "config.org")))
    (should (or (string-match-p "projectile-mode" content)
                (string-match-p "project-switch-project" content)
                (string-match-p "project\\.el" content)))
    (should (string-match-p "mode-line-format" content))
    (should-not (string-match-p "doom-modeline-mode" content))))

(ert-deftest config-should-support-org-and-markdown ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "org-mode" content))
    (should (string-match-p "org-startup-indented nil" content))
    (should (string-match-p "org-cycle" content))
    (should (or (string-match-p "markdown" content)
                (string-match-p "\\.md\\'" content)))))

(ert-deftest config-should-enable-visual-line-wrapping ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "global-visual-line-mode 1" content))
    (should (string-match-p "truncate-lines nil" content))
    (should (string-match-p "word-wrap t" content))
    (should-not (string-match-p "global-display-line-numbers-mode 1" content))
    (should (string-match-p "add-hook 'prog-mode-hook #'display-line-numbers-mode" content))
    (should-not (string-match-p "prog-mode-hook.*lambda.*display-line-numbers-mode" content))))

(ert-deftest legacy-lisp-modules-should-be-removed ()
  (should-not (file-directory-p (repo-file "lisp"))))

(ert-deftest config-should-auto-install-missing-packages ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "my/install-missing-packages" content))
    (should (string-match-p "my/auto-install-packages" content))
    (should (string-match-p "if my/auto-install-packages" content))
    (should (string-match-p "condition-case" content))
    (should (string-match-p "display-warning" content))
    (should (string-match-p "'my/init" content))))

(ert-deftest config-should-disable-backup-autosave-and-lockfiles ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "make-backup-files nil" content))
    (should (string-match-p "auto-save-default nil" content))
    (should (string-match-p "create-lockfiles nil" content))
    (should (string-match-p "auto-save-list-file-prefix nil" content))))

(ert-deftest config-should-enable-simple-global-keybindings ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "which-key" content))
    (should (string-match-p "(kbd \"C-c a\") #'org-agenda" content))
    (should (string-match-p "(kbd \"C-c c\") #'my/orgfiles-capture-dispatch" content))
    (should (string-match-p "(kbd \"C-c t\") #'my/orgfiles-capture-todo" content))
    (should (string-match-p "(kbd \"C-c T\") #'org-todo-list" content))
    (should (string-match-p "(kbd \"C-c s\") #'my/search-dispatch" content))
    (should (string-match-p "(kbd \"C-c g\") #'my/consult-ripgrep" content))
    (should (string-match-p "(kbd \"C-c l\") #'my/consult-line" content))
    (should (string-match-p "(kbd \"C-c r\") #'my/consult-recent-file" content))
    (should (string-match-p "(kbd \"C-c p\") #'my/project-switch-project" content))
    (should (string-match-p "(kbd \"C-c f\") #'my/project-find-file" content))
    (should (string-match-p "(kbd \"C-c d\") #'my/project-dired" content))
    (should (string-match-p "(kbd \"C-c \\+\") #'my/font-size-increase" content))
    (should (string-match-p "(kbd \"C-c -\") #'my/font-size-decrease" content))
    (should (string-match-p "(kbd \"C-c 0\") #'my/font-size-reset" content))))

(ert-deftest config-should-enable-modern-completion-stack ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "vertico" content))
    (should (string-match-p "vertico-mode 1" content))
    (should (string-match-p "orderless" content))
    (should (string-match-p "completion-styles '(orderless basic)" content))
    (should (string-match-p "consult" content))
    (should (string-match-p "consult-completion-in-region" content))
    (should (string-match-p "xref-show-xrefs-function #'consult-xref" content))
    (should (string-match-p "xref-show-definitions-function #'consult-xref" content))
    (should (string-match-p "advice-add #'register-preview :override #'consult-register-window" content))
    (should (string-match-p "defun my/consult-line" content))
    (should (string-match-p "fboundp 'consult-line" content))
    (should (string-match-p "isearch-forward" content))
    (should (string-match-p "defun my/consult-buffer" content))
    (should (string-match-p "switch-to-buffer" content))
    (should (string-match-p "defun my/consult-recent-file" content))
    (should (string-match-p "recentf-open-files" content))
    (should (string-match-p "defun my/consult-ripgrep" content))
    (should (string-match-p "rgrep" content))
    (should (string-match-p "defun my/consult-imenu" content))
    (should (string-match-p "consult-imenu" content))
    (should (string-match-p "defun my/search-dispatch" content))
    (should (string-match-p "\"current buffer\"" content))
    (should (string-match-p "\"project text\"" content))
    (should (string-match-p "\"symbols\"" content))
    (should (string-match-p "\"recent files\"" content))
    (should (string-match-p "marginalia" content))
    (should (string-match-p "marginalia-mode 1" content))
    (should (string-match-p "embark" content))
    (should (string-match-p "embark-act" content))
    (should (string-match-p "embark-export" content))
    (should (string-match-p "(kbd \"C-c C-o\") #'embark-export" content))
    (should (string-match-p "embark-consult" content))))

(ert-deftest config-should-have-mode-local-emacs-bindings ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "markdown-mode-map" content))
    (should (string-match-p "prog-mode-map" content))
    (should-not (string-match-p "(kbd \"C-c C-r\") #'org-refile" content))
    (should-not (string-match-p "(kbd \"C-c C-a\") #'org-archive-subtree" content))
    (should (string-match-p "(kbd \"C-c C-p\") #'markdown-preview" content))
    (should (string-match-p "(kbd \"C-c C-h\") #'markdown-insert-header-dwim" content))
    (should (string-match-p "(kbd \"C-c C-g\") #'xref-find-definitions" content))))

(ert-deftest config-should-support-meeting-note-capture ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "my/orgfiles-root" content))
    (should (string-match-p "ORGFILES_ROOT" content))
    (should (string-match-p "my/orgfiles-default-root" content))
    (should (string-match-p "~/Documents/" content))
    (should (string-match-p "Meeting name: " content))
    (should (string-match-p "Meeting time: " content))
    (should (string-match-p "org-read-date" content))
    (should (string-match-p "my/orgfiles--new-meeting-file" content))
    (should (string-match-p "my/orgfiles--meeting-template" content))
    (should (string-match-p "format-time-string \"%Y-%m-%d %a %H:%M\"" content))
    (should (string-match-p "\\* 背景" content))
    (should (string-match-p "\\* 结论（Decision）" content))
    (should (string-match-p "\\* 待办（Action Items）" content))
    (should (string-match-p "\\[#A\\]" content))
    (should (string-match-p "OWNER: 负责人" content))))

(ert-deftest config-should-support-idea-journal-and-brainstorm-notes ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "my/orgfiles-idea-file" content))
    (should (string-match-p "my/orgfiles-inbox-file" content))
    (should (string-match-p "inbox\\.org" content))
    (should (string-match-p "ideas\\.org" content))
    (should (string-match-p "file-name-as-directory" content))
    (should (string-match-p "my/orgfiles-capture-dispatch" content))
    (should (string-match-p "Capture type: " content))
    (should (string-match-p "'(\"todo\" \"brainstorm\" \"idea\" \"journal\" \"meeting\")" content))
    (should (string-match-p "my/orgfiles-capture-todo" content))
    (should (string-match-p "\"todo\" (my/orgfiles-capture-todo)" content))
    (should (string-match-p "\"t\" \"Todo\" entry" content))
    (should (string-match-p "file\\+headline my/orgfiles-inbox-file \"Tasks\"" content))
    (should (string-match-p "my/orgfiles-capture-brainstorm" content))
    (should (string-match-p "Brainstorm title: " content))
    (should (string-match-p "my/orgfiles--timestamped-file-path" content))
    (should (string-match-p "format-time-string \"%Y-%m-%d-%H%M\"" content))
    (should (string-match-p "my/orgfiles--new-brainstorm-file" content))
    (should-not (string-match-p "my/orgfiles--ensure-brainstorm-file" content))
    (should (string-match-p "my/orgfiles-capture-idea" content))
    (should (string-match-p "file\\+headline my/orgfiles-idea-file \"Ideas\"" content))
    (should-not (string-match-p "with-temp-file my/orgfiles-personal-file" content))
    (should (string-match-p "my/orgfiles-capture-journal" content))
    (should (string-match-p "my/orgfiles-capture-meeting" content))
    (should (string-match-p "org-capture-templates" content))
    (should (string-match-p "org-agenda-files" content))
    (should-not (string-match-p "(\"b\" \"Brainstorm\" entry" content))
    (should-not (string-match-p "brainstorm/" content))
    (should-not (string-match-p "journal/" content))
    (should-not (string-match-p "meetings/" content))
    (should (string-match-p "(\"i\" \"Idea\" entry" content))
    (should (string-match-p "(\"j\" \"Journal\" entry" content))))

(ert-deftest config-should-set-macos-modifiers ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "mac-command-modifier" content))
    (should (string-match-p "mac-option-modifier" content))))

(ert-deftest config-should-support-system-clipboard-copy ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "select-enable-clipboard t" content))
    (should (string-match-p "save-interprogram-paste-before-kill t" content))
    (should (string-match-p "defun my/copy-region-or-line" content))
    (should (string-match-p "kill-ring-save (region-beginning) (region-end)" content))
    (should (string-match-p "kill-ring-save (line-beginning-position) (line-end-position)" content))
    (should (string-match-p "(kbd \"C-c w\") #'my/copy-region-or-line" content))
    (should (string-match-p "(kbd \"s-c\") #'my/copy-region-or-line" content))
    (should (string-match-p "(kbd \"s-v\") #'yank" content))
    (should (string-match-p "(kbd \"s-x\") #'kill-region" content))))

(ert-deftest config-should-set-ayu-theme-and-adaptive-font-controls ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "ayu-theme" content))
    (should (string-match-p "load-theme 'ayu-light t" content))
    (should (string-match-p "defvar my/default-font-height" content))
    (should (string-match-p "display-pixel-width" content))
    (should (string-match-p "set-face-attribute 'default nil :height my/default-font-height" content))
    (should (string-match-p "defun my/font-size-reset" content))
    (should (string-match-p "defun my/font-size-increase" content))
    (should (string-match-p "defun my/font-size-decrease" content))))

(ert-deftest config-should-confirm-before-exit ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "defun my/confirm-kill-emacs" content))
    (should (string-match-p "setq confirm-kill-emacs #'my/confirm-kill-emacs" content))
    (should (string-match-p "Really quit Emacs\\?" content))))

(ert-deftest config-should-provide-manual-reload-command ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "defun my/reload-config" content))
    (should (string-match-p "org-babel-load-file" content))
    (should (string-match-p "expand-file-name \"config\\.org\" user-emacs-directory" content))))

(ert-deftest config-should-refresh-stale-buffer-on-focus-only ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "defun my/revert-current-buffer-on-focus" content))
    (should (string-match-p "focus-in-hook" content))
    (should (string-match-p "file-remote-p" content))
    (should-not (string-match-p "buffer-list-update-hook" content))
    (should (string-match-p "verify-visited-file-modtime" content))
    (should (string-match-p "revert-buffer :ignore-auto :noconfirm :preserve-modes" content))))

(ert-deftest config-should-sanitize-meeting-note-filename ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "my/orgfiles--safe-file-stem" content))
    (should (string-match-p "file-name-nondirectory" content))
    (should (string-match-p "string-trim collapsed" content))
    (should (string-match-p "untitled" content))
    (should (string-match-p "\\[:multibyte:\\]" content))))

(ert-deftest config-should-initialize-root-org-agenda-files-and-enable-refile ()
  (let ((content (file-content "config.org")))
    ;; Agenda is initialized from root org files at startup, excluding init.org setup notes.
    (should (string-match-p "defvar my/orgfiles-projects-dir" content))
    (should (string-match-p "\"projects\" my/orgfiles-root" content))
    (should (string-match-p "defun my/orgfiles-agenda-files" content))
    (should (string-match-p "directory-files my/orgfiles-root t" content))
    (should (string-match-p "\\\\\\\\.org\\\\\\\\'" content))
    (should (string-match-p "file-name-nondirectory file) \"init\\.org\"" content))
    (should (string-match-p "my/orgfiles--ensure-dir my/orgfiles-projects-dir" content))
    (should (string-match-p "(list my/orgfiles-projects-dir)" content))
    (should (string-match-p "org-agenda-files (my/orgfiles-agenda-files)" content))
    (should-not (string-match-p "org-agenda-files (list my/orgfiles-inbox-file" content))
    (should-not (string-match-p "org-agenda-files (list my/orgfiles-root)" content))
    ;; Refile configuration is present and points at agenda files.
    (should (string-match-p "org-refile-targets '((org-agenda-files :maxlevel \\. 3))" content))
    (should (string-match-p "org-refile-use-outline-path 'file" content))
    (should (string-match-p "org-outline-path-complete-in-steps nil" content))
    (should (string-match-p "org-refile-allow-creating-parent-nodes 'confirm" content))
    ;; Refile stays on Org's default binding instead of adding another custom layer.
    (should-not (string-match-p "(kbd \"C-c C-r\") #'org-refile" content))))
