(require 'ert)

(defconst repo-root
  (file-name-directory
   (directory-file-name
    (file-name-directory (or load-file-name buffer-file-name)))))

(defun repo-file (name)
  (expand-file-name name repo-root))

(defun file-content (name)
  (with-temp-buffer
    (insert-file-contents (repo-file name))
    (buffer-string)))

(ert-deftest config-org-should-exist ()
  (should (file-exists-p (repo-file "config.org"))))

(ert-deftest init-should-load-config-org ()
  (let ((content (file-content "init.el")))
    (should (string-match-p "org-babel-load-file" content))
    (should (string-match-p "config\\.org" content))))

(ert-deftest config-should-enable-evil-and-jk-escape ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "evil-mode" content))
    (should (or (string-match-p "key-chord-define" content)
                (string-match-p "jk.*escape\\|escape.*jk" content)))))

(ert-deftest config-should-have-project-and-statusline ()
  (let ((content (file-content "config.org")))
    (should (or (string-match-p "projectile-mode" content)
                (string-match-p "project-switch-project" content)
                (string-match-p "project\\.el" content)))
    (should (string-match-p "mode-line-format" content))
    (should-not (string-match-p "doom-modeline-mode" content))))

(ert-deftest config-should-support-org-and-markdown ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "org-mode" content))
    (should (string-match-p "org-cycle" content))
    (should (or (string-match-p "markdown" content)
                (string-match-p "\\.md\\'" content)))))

(ert-deftest config-should-enable-visual-line-wrapping ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "global-visual-line-mode 1" content))
    (should (string-match-p "truncate-lines nil" content))
    (should (string-match-p "word-wrap t" content))))

(ert-deftest legacy-lisp-modules-should-be-removed ()
  (should-not (file-directory-p (repo-file "lisp"))))

(ert-deftest config-should-auto-install-missing-packages ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "my/install-missing-packages" content))
    (should (string-match-p "my/auto-install-packages" content))
    (should (string-match-p "when my/auto-install-packages" content))))

(ert-deftest config-should-disable-backup-autosave-and-lockfiles ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "make-backup-files nil" content))
    (should (string-match-p "auto-save-default nil" content))
    (should (string-match-p "create-lockfiles nil" content))
    (should (string-match-p "auto-save-list-file-prefix nil" content))))

(ert-deftest config-should-enable-space-style-keybindings ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "general" content))
    (should (string-match-p "which-key" content))
    (should (string-match-p ":prefix \"SPC\"" content))
    (should (string-match-p ":prefix \",\"" content))
    (should (string-match-p "\"SPC\" #'execute-extended-command" content))
    (should (string-match-p "\"a o a\" #'org-agenda" content))
    (should (string-match-p "\"a o c\" #'my/orgfiles-capture-dispatch" content))
    (should-not (string-match-p "\"a o c c\" #'org-capture" content))
    (should-not (string-match-p "\"a o c i\" #'my/orgfiles-capture-idea" content))
    (should-not (string-match-p "\"a o c j\" #'my/orgfiles-capture-journal" content))
    (should-not (string-match-p "\"a o c m\" #'my/orgfiles-new-note" content))
    (should-not (string-match-p "\"a o i\" #'my/orgfiles-capture-idea" content))
    (should-not (string-match-p "\"a o j\" #'my/orgfiles-capture-journal" content))
    (should-not (string-match-p "\"a o n\" #'my/orgfiles-new-note" content))
    (should (string-match-p "\"f f\" #'find-file" content))
    (should (string-match-p "\"f g\" #'consult-ripgrep" content))
    (should (string-match-p "\"f l\" #'consult-line" content))
    (should (string-match-p "\"f r\" #'consult-recent-file" content))
    (should-not (string-match-p "\"n n\" #'my/orgfiles-new-note" content))
    (should (string-match-p "\"b b\" #'consult-buffer" content))
    (should (string-match-p "\"p p\" #'projectile-switch-project" content))
    (should (string-match-p "\"p r\" #'projectile-recentf" content))
    (should (string-match-p "\"p d\" #'projectile-dired" content))
    (should (string-match-p "\"w /\" #'split-window-right" content))))

(ert-deftest config-should-enable-modern-completion-stack ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "vertico" content))
    (should (string-match-p "vertico-mode 1" content))
    (should (string-match-p "orderless" content))
    (should (string-match-p "completion-styles '(orderless basic)" content))
    (should (string-match-p "consult" content))
    (should (string-match-p "consult-completion-in-region" content))
    (should (string-match-p "xref-show-xrefs-function #'consult-xref" content))
    (should (string-match-p "xref-show-definitions-function #'consult-xref" content))
    (should (string-match-p "advice-add #'register-preview :override #'consult-register-window" content))
    (should (string-match-p "marginalia" content))
    (should (string-match-p "marginalia-mode 1" content))
    (should (string-match-p "embark" content))
    (should (string-match-p "embark-act" content))
    (should (string-match-p "embark-export" content))
    (should (string-match-p "(kbd \"C-c C-o\") #'embark-export" content))
    (should (string-match-p "embark-consult" content))))

(ert-deftest config-should-have-local-leader-for-main-modes ()
  (let ((content (file-content "config.org")))
    (should (string-match-p ":keymaps 'org-mode-map" content))
    (should (string-match-p ":keymaps 'markdown-mode-map" content))
    (should (string-match-p ":keymaps 'prog-mode-map" content))
    (should (string-match-p "\"t\" #'org-todo" content))
    (should (string-match-p "\"h\" #'markdown-insert-header-dwim" content))
    (should (string-match-p "\"g\" #'xref-find-definitions" content))))

(ert-deftest config-should-support-meeting-note-capture ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "my/orgfiles-root" content))
    (should (string-match-p "~/code/orgfiles/" content))
    (should (string-match-p "Meeting name: " content))
    (should (string-match-p "expand-file-name \"meetings/\" my/orgfiles-root" content))
    (should (string-match-p "my/orgfiles--meeting-template" content))
    (should (string-match-p "\\* 背景" content))
    (should (string-match-p "\\* 结论（Decision）" content))
    (should (string-match-p "\\* 待办（Action Items）" content))
    (should (string-match-p "\\[#A\\]" content))
    (should (string-match-p "OWNER: 负责人" content))))

(ert-deftest config-should-support-idea-and-journal-capture ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "my/orgfiles-idea-file" content))
    (should (string-match-p "ideas\\.org" content))
    (should (string-match-p "my/orgfiles-journal-dir" content))
    (should (string-match-p "journal/" content))
    (should (string-match-p "my/orgfiles-capture-dispatch" content))
    (should (string-match-p "Capture type: " content))
    (should (string-match-p "'(\"idea\" \"journal\" \"meeting\")" content))
    (should (string-match-p "my/orgfiles-capture-idea" content))
    (should (string-match-p "my/orgfiles-capture-journal" content))
    (should (string-match-p "org-capture-templates" content))
    (should (string-match-p "(\"i\" \"Idea\" entry" content))
    (should (string-match-p "(\"j\" \"Journal\" entry" content))))

(ert-deftest config-should-set-macos-modifiers ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "mac-command-modifier" content))
    (should (string-match-p "mac-option-modifier" content))))

(ert-deftest config-should-set-ayu-theme-and-larger-font ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "ayu-theme" content))
    (should (string-match-p "load-theme 'ayu-light t" content))
    (should (string-match-p "set-face-attribute 'default nil :height 160" content))))

(ert-deftest config-should-confirm-before-exit ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "defun my/confirm-kill-emacs" content))
    (should (string-match-p "setq confirm-kill-emacs #'my/confirm-kill-emacs" content))
    (should (string-match-p "Really quit Emacs\\?" content))))

(ert-deftest config-should-provide-manual-reload-command ()
  (let ((content (file-content "config.org")))
    (should (string-match-p "defun load-my-config" content))
    (should (string-match-p "org-babel-load-file" content))
    (should (string-match-p "expand-file-name \"config\\.org\" user-emacs-directory" content))))
